version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - restore_cache:
          key: prose-pre-commit-hooks-env-{{ checksum "requirements-test.txt" }}
      - run:
          name: Install dependencies
          command: |
            make init-ci
      - save_cache:
          key: prose-pre-commit-hooks-env-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          name: Run test
          command: venv/bin/python3 -m pytest --cov=prose tests

  check_version:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - restore_cache:
          key: prose-pre-commit-hooks-env-{{ checksum "requirements-test.txt" }}
      - run:
          name: Install dependencies
          command: |
            make init-ci
      - save_cache:
          key: prose-pre-commit-hooks-env-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            venv/bin/python setup.py verify


workflows:
  version: 2
  build:
    jobs:
      - build_and_test
      - check_version:
          requires:
            - build_and_test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              only:
                - main
