- id: manage-airflow-dag-task-id
  name: airflow dag and task consistency hook
  description: airflow dag and task consistency hook
  entry: manage-airflow-dag-task-id
  language: python
  always_run: true
  pass_filenames: true
  types: [file, python]
  files: (^|/)dag_.+\.py

- id: add-clubhouse-ticket
  name: add cluchouse ticket ref
  description: Automatically append [chXXX] to the commit message
  entry: add-clubhouse-ticket
  language: python
  stages: [prepare-commit-msg]
  always_run: true
  verbose: true

- id: check-prose-data-blog-rmd-file-pattern
  name: check prose-data-blog filename pattern
  description: Check that the blog Rmd follow the pattern YYYY-MM-DD_ch0000_XXX.Rmd
  entry: check-prose-data-blog-rmd-file-pattern
  language: python
  always_run: true
  pass_filenames: true
  types: [file, python]
  files: content/blog/*.Rmd
