repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [
        'flake8-awesome',
        'flake8-blind-except',
        'flake8-deprecated',
        'flake8-meiqia',
        'flake8-mutable',
        'flake8-pep3101',
        'flake8-string-format']
        exclude: ^tests/
        args: ['--config=setup.cfg']

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: debug-statements
    -   id: check-docstring-first

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.19.1
    hooks:
    -   id: pyupgrade

-   repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
    - id: black
      language_version: python3.7

-   repo: local
    hooks:
    - id: tests
      name: run tests
      entry: venv/bin/pytest -v
      language: system
      types: [python]
      stages: [push]
