-   id: manage-airflow-dag-task-id
    name: airflow dag and task consistency hook
    description: airflow dag and task consistency hook
    entry: manage-airflow-dag-task-id
    language: python
    always_run: true
    pass_filenames: true
    types: [file, python]
    files: (^|/)dag_.+\.py
