version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - restore_cache:
          key: prose-pre-commit-hooks-env-{{ checksum "requirements-test.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            venv/bin/pip install --disable-pip-version-check -U pip
            venv/bin/pip install -r requirements-test.txt
      - save_cache:
          key: prose-pre-commit-hooks-env-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          name: Run test
          command: venv/bin/python3 -m pytest --cov=prose tests

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
